package de.peterspan.csv2db;

import java.sql.Connection;
import java.sql.Statement;

public class DatabaseSetup {

	
	public static void setup(Connection con){
		try{
			Statement stm = con.createStatement();
			
			//CREATE MEMORY TABLE PUBLIC.CUSTOMER(CUSTOMER_ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 2) NOT NULL PRIMARY KEY,CUSTOMER_FIRSTNAME VARCHAR(128),CUSTOMER_LASTNAME VARCHAR(128),CUSTOMER_EMAIL VARCHAR(128),CUSTOMER_PASSWORD VARCHAR(64))
			stm.execute("CREATE TABLE location (id INT NOT NULL PRIMARY KEY, Name varchar(255))");
		}catch(Exception e){
			System.out.println("Exception durign setup "+e+" "+e.getStackTrace());
		}
		
	}
}
